name: lxd
version: git
grade: devel
summary: LXD - the container lightervisor
description: LXD is a container manager for system containers.
 It offers a REST API to remotely manage containers over the network,
 using an image based workflow and with support for live migration.

 Images are available for all Ubuntu releases and architectures as well
 as for a wide number of other Linux distributions.

 LXD containers are lightweight, secure by default and a great
 alternative to virtual machines.
confinement: strict

apps:
  benchmark:
    command: wrappers/lxd-benchmark
    plugs: [lxd-support]
  check-kernel:
    command: wrappers/lxd-check-kernel
    plugs: [lxd-support]
  daemon:
    command: wrappers/daemon.start
#    reload-command: wrappers/daemon.reload
    stop-command: wrappers/daemon.stop
    stop-timeout: 600s
    restart-condition: always
    daemon: simple
    plugs: [lxd-support]
    slots: [lxd]
  lxc:
    command: wrappers/lxc
    plugs: [lxd-support]
    aliases: [lxc]
    completer: etc/bash_completion.d/snap.lxd.lxc
  lxd:
    command: wrappers/lxd
    plugs: [lxd-support]
  migrate:
    command: wrappers/lxd-migrate
    plugs: [lxd-support]

hooks:
  configure:
    plugs: [network]

parts:
  # Dependencies
  btrfs:
    plugin: nil
    stage-packages:
      - btrfs-tools
    prime:
      - bin/btrfs
      - bin/mkfs.btrfs

  go:
    source-tag: go1.8.3

  lvm:
    plugin: nil
    stage-packages:
      - dmeventd
      - lvm2
      - thin-provisioning-tools
    organize:
      sbin/: bin/
      usr/lib/: lib/
      usr/sbin/: bin/
    prime:
      - bin/cache_*
      - bin/dmeventd
      - bin/era_*
      - bin/lv*
      - bin/pdata_tools
      - bin/pv*
      - bin/thin_*
      - bin/vg*
      - etc/lvm/lvm.conf
      - lib/*/device-mapper/*
      - lib/*/libaio.so*
      - lib/*/libdevmapper*
      - lib/*/liblvm*
      - lib/*/libreadline.so*

  openvswitch:
    plugin: nil
    stage-packages:
      - openvswitch-switch
      - uuid-runtime
    organize:
      usr/bin/: bin/
      usr/lib/openvswitch-switch/: bin/
      usr/sbin/: bin/
      usr/share/: share/
    prime:
      - bin/ovs-*
      - bin/ovsdb-*
      - bin/uuidgen
      - share/openvswitch/

  zfs:
    plugin: nil
    stage-packages:
      - zfsutils-linux
    organize:
      sbin/: bin/
      usr/lib/: lib/
    prime:
      - bin/zfs
      - bin/zpool
      - lib/libnvpair.so.*
      - lib/libuutil.so.*
      - lib/libzfs_core.so.*
      - lib/libzfs.so.*
      - lib/libzpool.so.*

  # Core components
  lxc:
    source: https://github.com/lxc/lxc
    source-type: git
    source-branch: stable-2.0
    build-packages:
      - libapparmor-dev
      - libcap-dev
      - libgnutls28-dev
      - libseccomp-dev
      - pkg-config
    plugin: autotools
    configflags:
      - --disable-selinux
      - --disable-python
      - --disable-lua
      - --disable-tests
      - --disable-examples
      - --disable-doc
      - --disable-api-docs
      - --disable-bash
      - --disable-cgmanager
      - --enable-apparmor
      - --enable-seccomp
      - --enable-capabilities
      - --with-rootfs-path=/var/snap/lxd/common/lxc/
      - --libexecdir=/snap/lxd/current/libexec/
    organize:
      snap/lxd/current/lxc: lxc
      snap/lxd/current/libexec: libexec
    prime:
      - bin/lxc-checkconfig
      - lib/liblxc.so.1
      - lib/liblxc.so.1.2.0
      - libexec/lxc/lxc-monitord
      - lxc/config/common.conf.d
    install: |-
      mkdir -p $SNAPCRAFT_PART_INSTALL/lxc/config/common.conf.d/
      ln -s /var/snap/lxd/common/lxc/local.conf $SNAPCRAFT_PART_INSTALL/lxc/config/common.conf.d/01-local.conf
      sed -i "s#includedir=.*#includedir=$SNAPCRAFT_PART_INSTALL/include#g" $SNAPCRAFT_PART_INSTALL/lib/pkgconfig/lxc.pc
      sed -i "s#libdir=.*#libdir=$SNAPCRAFT_PART_INSTALL/lib#g" $SNAPCRAFT_PART_INSTALL/lib/pkgconfig/lxc.pc

  lxcfs:
    source: https://github.com/lxc/lxcfs
    source-type: git
    source-branch: stable-2.0
    build-packages:
      - libfuse-dev
      - libpam0g-dev
      - pkg-config
    stage-packages:
      - fuse
    plugin: autotools
    configflags:
      - --datarootdir=/snap/lxd/current/
      - --localstatedir=/var/snap/lxd/common/var/
    organize:
      snap/lxd/current/lxc: lxc
      snap/lxd/current/lxcfs: lxcfs
    prime:
      - bin/fusermount
      - lib/*/libfuse.so.*

      - bin/lxcfs
      - lib/liblxcfs.so
      - lib/liblxcfs.so.*

      - lxc
      - lxcfs

  lxd:
    source: https://github.com/lxc/lxd
    source-type: git
    source-branch: stable-2.0
    prepare: |-
      cd ../src
      git am ../../../patches/0001-Add-support-for-lxd-bridge-configuration-snap.patch
      cp lxd-bridge/lxd-bridge $SNAPCRAFT_PART_INSTALL/bin/
      sed -i "s#^config=.*#config=\${SNAP_COMMON}/lxd-bridge/config#g" $SNAPCRAFT_PART_INSTALL/bin/lxd-bridge
      sed -i "s#^varrun=.*#varrun=\${SNAP_COMMON}/lxd-bridge/run#g" $SNAPCRAFT_PART_INSTALL/bin/lxd-bridge
      sed -i "s#^varlib=.*#varlib=\${SNAP_COMMON}/lxd-bridge/lib#g" $SNAPCRAFT_PART_INSTALL/bin/lxd-bridge
      sed -i "s#^LXD_BRIDGE=\"lxdbr0\"#LXD_BRIDGE=\"\"#g" $SNAPCRAFT_PART_INSTALL/bin/lxd-bridge
      sed -i "s#^USE_LXD_BRIDGE=\"true\"#USE_LXD_BRIDGE=\"false\"#g" $SNAPCRAFT_PART_INSTALL/bin/lxd-bridge
      sed -i "s#^LXD_IPV6_PROXY=\"true\"#LXD_IPV6_PROXY=\"false\"#g" $SNAPCRAFT_PART_INSTALL/bin/lxd-bridge
    after:
      - go
      - lxc
    build-packages:
      - pkg-config
      - libacl1-dev
      - libsqlite3-dev
    stage-packages:
      - acl
      - dnsmasq-base
      - ebtables
      - rsync
      - squashfs-tools
      - vim-tiny
    plugin: go
    go-buildtags:
      - libsqlite3
    go-importpath: github.com/lxc/lxd
    go-packages:
      - github.com/lxc/lxd/lxc
      - github.com/lxc/lxd/lxd
      - github.com/lxc/lxd/test/lxd-benchmark
    install: |-
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/etc/bash_completion.d/
      cp ../src/config/bash/lxd-client ${SNAPCRAFT_PART_INSTALL}/etc/bash_completion.d/snap.lxd.lxc
    organize:
      usr/bin/: bin/
      usr/lib/: lib/
      usr/sbin/: bin/
      sbin/: bin/
      usr/share/vim/vim74/debian.vim: etc/vimrc
    prime:
      - bin/dnsmasq
      - bin/ebtables
      - bin/rsync
      - bin/setfacl
      - bin/unsquashfs
      - bin/vim.tiny
      - lib/*/libsqlite3*

      - etc/vimrc
      - etc/bash_completion.d/snap.lxd.lxc

      - bin/lxc
      - bin/lxd
      - bin/lxd-benchmark
      - bin/lxd-bridge

  lxd-migrate:
    source: lxd-migrate/
    after:
      - go
      - lxd
    build-packages:
      - libsqlite3-dev
    plugin: go
    go-buildtags:
      - libsqlite3
    go-importpath: github.com/lxc/lxd-pkg-snap/lxd-migrate
    install: |-
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/bin/
      cp scripts/upgrade-bridge ${SNAPCRAFT_PART_INSTALL}/bin/upgrade-bridge
    prime:
      - bin/lxd-migrate
      - bin/upgrade-bridge

  wrappers:
    plugin: dump
    source: snapcraft/
    organize:
      hooks/: snap/hooks/
