# This is a basic workflow to help you get started with Actions

name: arm64 CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the latest-candidate branch
  push:
    branches: [ latest-candidate ]
  pull_request:
    branches: [ latest-candidate ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: [self-hosted, Linux, ARM64]
    steps:
    - uses: actions/checkout@v2
    - uses: snapcore/action-build@v1
      id: snapcraft
    - uses: actions/upload-artifact@v2
      with:
        name: snap
        path: ${{ steps.snapcraft.outputs.snap }}
