name: arm64 CI
 
on:
  push:
    branches:
    - latest-candidate
 
jobs:
  build-stable:
    runs-on: ubuntu-latest
    
    # Let's build for many architectures..
    strategy:
      matrix:
        architecture:
        - arm64
    steps:
    # Checkout the code of our Repository
    - uses: actions/checkout@v2

    # Do the build!
    - uses: diddlesnaps/snapcraft-multiarch-action@v1
      id: snapcraft
      with:
        architecture: ${{ matrix.architecture }}
    - uses: actions/upload-artifact@v3
      with:
        name: snap
        path: ${{ steps.snapcraft.outputs.snap }}
